services:

  producer:
    build: ./producer
    container_name: producer
    depends_on:
      - fluentd
    env_file:
      - .env
    networks:
      tap:

  fluentd:
    build: ./fluentd
    container_name: fluentd
    depends_on:
      - kafka_broker
    volumes:
      - ./fluentd/conf:/fluentd/etc/
    restart: always
    command: >
             bash -c 'fluentd -c /fluentd/etc/fluentd.conf'
    mem_limit: 512m
    networks:
      tap:
        ipv4_address: 10.0.100.21
  
  kafka_zookeeper:
    build: ./kafka
    container_name: kafka_zookeeper
    ports:
      - 2181:2181
    command: > 
      bash -c "set -v
               mkdir -p /tmp/zookeeper
               cd /opt/kafka
               zookeeper-server-start.sh config/zookeeper.properties"
    networks:
      tap:
        ipv4_address: 10.0.100.22

  
  kafka_broker:
    build: ./kafka
    container_name: kafka_broker
    depends_on:
      - kafka_zookeeper
    ports:
      - 9092:9092
    command: > 
      bash -c "set -v
               cd /opt/kafka
               kafka-server-start.sh config/server.properties"
    networks:
      tap:
        ipv4_address: 10.0.100.23


  telegram_msg_topic:
    build: ./kafka
    container_name: telegram_msg_topic
    command: > 
      bash -c "set -v
               cd /opt/kafka
               kafka-topics.sh --bootstrap-server 10.0.100.23:9092 --list
               kafka-topics.sh --create --bootstrap-server 10.0.100.23:9092 --replication-factor 1 --partitions 1 --topic msg_telegram
               kafka-topics.sh --bootstrap-server 10.0.100.23:9092 --list"
    depends_on: 
        - kafka_broker
    networks:
      tap:

  kafka_ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafkaUI
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=10.0.100.23:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=10.0.100.22:2181
    ports:
      - "8080:8080"
    networks:
      tap:
  
  spark:
    build: ./spark
    container_name: spark
    volumes:
      - C:\Users\stran\OneDrive\Desktop\TeleSummary\spark:/TeleSummary/spark
    ports:
      - 4040:4040
    depends_on:
      - producer
      - elasticsearch
    networks:
        tap:
    mem_limit: 6g
    environment:
      - SPARK_DRIVER_MEMORY=3g
      - SPARK_EXECUTOR_MEMORY=3g

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    container_name: elasticsearch
    ports:
      - 9200:9200
    networks:
      tap:
        ipv4_address: 10.0.100.25

networks:
    tap:
        name: tap
        driver: bridge
        ipam: 
            config:
                 - subnet: 10.0.100.0/24
        external: true
