services:

  producer:
    build: ./producer
    container_name: producer
    depends_on:
      - fluentd
    env_file:
      - .env
    networks:
      tap:

  fluentd:
    build: ./fluentd
    container_name: fluentd
    #depends_on:
    #  - kafka_broker
    volumes:
      - ./fluentd/conf:/fluentd/etc/
    restart: always
    command: >
             bash -c 'fluentd -c /fluentd/etc/fluentd.conf'
    mem_limit: 512m
    networks:
      tap:
        ipv4_address: 10.0.100.21
  

networks:
    tap:
        name: tap
        driver: bridge
        ipam: 
            config:
                 - subnet: 10.0.100.1/24
        external: true
